### PR TITLE
manifest add woff2

### LINKED ISSUE #8: Missing WOFF2 support
This distribution is missing the WOFF2 libraries. See https://github.com/fontforge/fontforge/blob/dd65d353d82f9eb9be70304352956f5d35a8217b/cmake/packages/FindWOFF2.cmake

This problems causes the WOFF2 format option to be missing in the File: Generate Font dialog.

Version: 20200314

### PR DESCRIPTION
**Pull request by muelli**
fixes https://github.com/flathub/org.fontforge.FontForge/issues/8

### CODE REVIEW

**Comment by hfiguiere** [comment]
I have do have a question with this PR. Brotli is in 20.08, so is there a reason to build it here?

I'm re-working the texlive Sdk package and I needed to add woff2 support. I found this here, it builds without adding brotli, albeit with brotli support, so I was wondering if I wasn't missing something.

**Comment by muelli** [comment]
> Brotli is in 20.08, so is there a reason to build it here?

Ah! I guess I wasn't aware.
Do you feel like patching it out?

**Comment by hfiguiere** [comment]
I can add that to my todo list.

**Comment by muelli** [comment]
I've removed it now :)

**Pull request merged**
